use iced::widget::svg::Handle;
use iced::widget::Svg;

use crate::countries::flags_pictures::{
    AU, BOGON, CA, CN, COMPUTER, DE, FR, GB, HOME, IN, JP, KR, UNKNOWN, US,
};
use crate::countries::types::country::Country;
use crate::gui::styles::svg::SvgType;
use crate::translations::translations_2::{
    local_translation, unknown_translation, your_network_adapter_translation,
};
use crate::translations::translations_4::reserved_address_translation;
use crate::translations::types::language::Language;
use crate::StyleType;

fn get_flag_from_country<'a>(
    country: Country,
    width: f32,
    is_local: bool,
    is_loopback: bool,
    is_bogon: Option<&str>,
    language: Language,
) -> (Svg<'a, StyleType>, String) {
    #![allow(clippy::too_many_lines)]
    let mut tooltip = country.to_string();
    let mut svg_style = SvgType::Standard;
    let svg = Svg::new(Handle::from_memory(Vec::from(match country {
        Country::AD => UNKNOWN,
        Country::AE => UNKNOWN,
        Country::AF => UNKNOWN,
        Country::AG => UNKNOWN,
        Country::AI => UNKNOWN,
        Country::AL => UNKNOWN,
        Country::AM => UNKNOWN,
        Country::AO => UNKNOWN,
        Country::AQ => UNKNOWN,
        Country::AR => UNKNOWN,
        Country::AS => UNKNOWN,
        Country::AT => UNKNOWN,
        Country::AU | Country::HM => AU,
        Country::AW => UNKNOWN,
        Country::AX => UNKNOWN,
        Country::AZ => UNKNOWN,
        Country::BA => UNKNOWN,
        Country::BB => UNKNOWN,
        Country::BD => UNKNOWN,
        Country::BE => UNKNOWN,
        Country::BF => UNKNOWN,
        Country::BG => UNKNOWN,
        Country::BH => UNKNOWN,
        Country::BI => UNKNOWN,
        Country::BJ => UNKNOWN,
        Country::BM => UNKNOWN,
        Country::BN => UNKNOWN,
        Country::BO => UNKNOWN,
        Country::BR => UNKNOWN,
        Country::BS => UNKNOWN,
        Country::BT => UNKNOWN,
        Country::BV => UNKNOWN,
        Country::BW => UNKNOWN,
        Country::BY => UNKNOWN,
        Country::BZ => UNKNOWN,
        Country::CA => CA,
        Country::CC => UNKNOWN,
        Country::CD => UNKNOWN,
        Country::CF => UNKNOWN,
        Country::CG => UNKNOWN,
        Country::CH => UNKNOWN,
        Country::CI => UNKNOWN,
        Country::CK => UNKNOWN,
        Country::CL => UNKNOWN,
        Country::CM => UNKNOWN,
        Country::CN => CN,
        Country::CO => UNKNOWN,
        Country::CR => UNKNOWN,
        Country::CU => UNKNOWN,
        Country::CV => UNKNOWN,
        Country::CW => UNKNOWN,
        Country::CX => UNKNOWN,
        Country::CY => UNKNOWN,
        Country::CZ => UNKNOWN,
        Country::DE => DE,
        Country::DJ => UNKNOWN,
        Country::DK => UNKNOWN,
        Country::DM => UNKNOWN,
        Country::DO => UNKNOWN,
        Country::DZ => UNKNOWN,
        Country::EC => UNKNOWN,
        Country::EE => UNKNOWN,
        Country::EG => UNKNOWN,
        Country::EH => UNKNOWN,
        Country::ER => UNKNOWN,
        Country::ES => UNKNOWN,
        Country::ET => UNKNOWN,
        Country::FI => UNKNOWN,
        Country::FJ => UNKNOWN,
        Country::FK => UNKNOWN,
        Country::FM => UNKNOWN,
        Country::FO => UNKNOWN,
        Country::FR
        | Country::BL
        | Country::GF
        | Country::GP
        | Country::MF
        | Country::MQ
        | Country::PM
        | Country::RE
        | Country::WF
        | Country::YT => FR,
        Country::GA => UNKNOWN,
        Country::GB => GB,
        Country::GD => UNKNOWN,
        Country::GE => UNKNOWN,
        Country::GG => UNKNOWN,
        Country::GH => UNKNOWN,
        Country::GI => UNKNOWN,
        Country::GL => UNKNOWN,
        Country::GM => UNKNOWN,
        Country::GN => UNKNOWN,
        Country::GQ => UNKNOWN,
        Country::GR => UNKNOWN,
        Country::GS => UNKNOWN,
        Country::GT => UNKNOWN,
        Country::GU => UNKNOWN,
        Country::GW => UNKNOWN,
        Country::GY => UNKNOWN,
        Country::HK => UNKNOWN,
        Country::HN => UNKNOWN,
        Country::HR => UNKNOWN,
        Country::HT => UNKNOWN,
        Country::HU => UNKNOWN,
        Country::ID => UNKNOWN,
        Country::IE => UNKNOWN,
        Country::IL => UNKNOWN,
        Country::IM => UNKNOWN,
        Country::IN => IN,
        Country::IO => UNKNOWN,
        Country::IQ => UNKNOWN,
        Country::IR => UNKNOWN,
        Country::IS => UNKNOWN,
        Country::IT => UNKNOWN,
        Country::JE => UNKNOWN,
        Country::JM => UNKNOWN,
        Country::JO => UNKNOWN,
        Country::JP => JP,
        Country::KE => UNKNOWN,
        Country::KG => UNKNOWN,
        Country::KH => UNKNOWN,
        Country::KI => UNKNOWN,
        Country::KM => UNKNOWN,
        Country::KN => UNKNOWN,
        Country::KP => UNKNOWN,
        Country::KR => KR,
        Country::KW => UNKNOWN,
        Country::KY => UNKNOWN,
        Country::KZ => UNKNOWN,
        Country::LA => UNKNOWN,
        Country::LB => UNKNOWN,
        Country::LC => UNKNOWN,
        Country::LI => UNKNOWN,
        Country::LK => UNKNOWN,
        Country::LR => UNKNOWN,
        Country::LS => UNKNOWN,
        Country::LT => UNKNOWN,
        Country::LU => UNKNOWN,
        Country::LV => UNKNOWN,
        Country::LY => UNKNOWN,
        Country::MA => UNKNOWN,
        Country::MC => UNKNOWN,
        Country::MD => UNKNOWN,
        Country::ME => UNKNOWN,
        Country::MG => UNKNOWN,
        Country::MH => UNKNOWN,
        Country::MK => UNKNOWN,
        Country::ML => UNKNOWN,
        Country::MM => UNKNOWN,
        Country::MN => UNKNOWN,
        Country::MO => UNKNOWN,
        Country::MP => UNKNOWN,
        Country::MR => UNKNOWN,
        Country::MS => UNKNOWN,
        Country::MT => UNKNOWN,
        Country::MU => UNKNOWN,
        Country::MV => UNKNOWN,
        Country::MW => UNKNOWN,
        Country::MX => UNKNOWN,
        Country::MY => UNKNOWN,
        Country::MZ => UNKNOWN,
        Country::NA => UNKNOWN,
        Country::NC => UNKNOWN,
        Country::NE => UNKNOWN,
        Country::NF => UNKNOWN,
        Country::NG => UNKNOWN,
        Country::NI => UNKNOWN,
        Country::NL | Country::BQ => UNKNOWN,
        Country::NO | Country::SJ => UNKNOWN,
        Country::NP => UNKNOWN,
        Country::NR => UNKNOWN,
        Country::NU => UNKNOWN,
        Country::NZ => UNKNOWN,
        Country::OM => UNKNOWN,
        Country::PA => UNKNOWN,
        Country::PE => UNKNOWN,
        Country::PF => UNKNOWN,
        Country::PG => UNKNOWN,
        Country::PH => UNKNOWN,
        Country::PK => UNKNOWN,
        Country::PL => UNKNOWN,
        Country::PN => UNKNOWN,
        Country::PR => UNKNOWN,
        Country::PS => UNKNOWN,
        Country::PT => UNKNOWN,
        Country::PW => UNKNOWN,
        Country::PY => UNKNOWN,
        Country::QA => UNKNOWN,
        Country::RO => UNKNOWN,
        Country::RS => UNKNOWN,
        Country::RU => UNKNOWN,
        Country::RW => UNKNOWN,
        Country::SA => UNKNOWN,
        Country::SB => UNKNOWN,
        Country::SC => UNKNOWN,
        Country::SD => UNKNOWN,
        Country::SE => UNKNOWN,
        Country::SG => UNKNOWN,
        Country::SH => UNKNOWN,
        Country::SI => UNKNOWN,
        Country::SK => UNKNOWN,
        Country::SL => UNKNOWN,
        Country::SM => UNKNOWN,
        Country::SN => UNKNOWN,
        Country::SO => UNKNOWN,
        Country::SR => UNKNOWN,
        Country::SS => UNKNOWN,
        Country::ST => UNKNOWN,
        Country::SV => UNKNOWN,
        Country::SX => UNKNOWN,
        Country::SY => UNKNOWN,
        Country::SZ => UNKNOWN,
        Country::TC => UNKNOWN,
        Country::TD => UNKNOWN,
        Country::TF => UNKNOWN,
        Country::TG => UNKNOWN,
        Country::TH => UNKNOWN,
        Country::TJ => UNKNOWN,
        Country::TK => UNKNOWN,
        Country::TL => UNKNOWN,
        Country::TM => UNKNOWN,
        Country::TN => UNKNOWN,
        Country::TO => UNKNOWN,
        Country::TR => UNKNOWN,
        Country::TT => UNKNOWN,
        Country::TV => UNKNOWN,
        Country::TW => UNKNOWN,
        Country::TZ => UNKNOWN,
        Country::UA => UNKNOWN,
        Country::UG => UNKNOWN,
        Country::US | Country::UM => US,
        Country::UY => UNKNOWN,
        Country::UZ => UNKNOWN,
        Country::VA => UNKNOWN,
        Country::VC => UNKNOWN,
        Country::VE => UNKNOWN,
        Country::VG => UNKNOWN,
        Country::VI => UNKNOWN,
        Country::VN => UNKNOWN,
        Country::VU => UNKNOWN,
        Country::WS => UNKNOWN,
        Country::YE => UNKNOWN,
        Country::ZA => UNKNOWN,
        Country::ZM => UNKNOWN,
        Country::ZW => UNKNOWN,
        Country::ZZ => {
            let (flag, new_tooltip) = if is_loopback {
                (
                    COMPUTER,
                    your_network_adapter_translation(language).to_string(),
                )
            } else if is_local {
                (HOME, local_translation(language).to_string())
            } else if let Some(bogon) = is_bogon {
                (BOGON, reserved_address_translation(language, bogon))
            } else {
                (UNKNOWN, unknown_translation(language).to_string())
            };

            svg_style = SvgType::AdaptColor;
            tooltip = new_tooltip;
            flag
        }
    })))
    .class(svg_style)
    .width(width)
    .height(width * 0.75);
    (svg, tooltip)
}

#[test]
fn test_country_utils() {
    let country = get_flag_from_country(Country::ZZ, 20.0, true, false, None, Language::ZH);
    assert_eq!(country.1, ("局域网").to_string());
}
