[package]
name = "learn-rust"
version = "0.1.0"
edition = "2021"

[workspace.package]
edition = "2021"
homepage = "https://stanic.xyz/"
license = "Mulan PSL v2"
repository = "https://stanic.xyz"

[workspace]
members = [
    "crates/dns_manager",
    "crates/domain_client",
    "crates/hello-game",
    "crates/test_db",
    "crates/domain_server",
    "crates/domain_manager",
    "crates/http_server"]
resolver = "2"

[dependencies]

[workspace.dependencies]
concurrency = { version = "0.1.0", path = "./crates/concurrency" }
