[workspace]
members = ["./crates/*", "crates/dns_manager", "crates/domain_client", "crates/hello-game", "crates/test_db"]
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://stanic.xyz/"
license = "Mulan PSL v2"
repository = "https://stanic.xyz"

[package]
name = "learn-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-ws = "0.3.0"
futures-util = "0.3.31"

[workspace.dependencies]
concurrency = { version = "0.1.0", path = "./crates/concurrency" }
domain_manager = { version = "0.1.0", path = "./crates/domain_manager" }
dns_manager = { version = "0.1.0", path = "./crates/dns_manager" }
test_db = { version = "0.1.0", path = "./crates/test_db" }
hello-wasm = { version = "0.1.1", package = "hello-wasm", path = "./crates/hello-wasm" }
