[package]
name = "test_db"
version = "0.1.0"
homepage.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"

[dependencies]
postgres = "0.19.4"
postgres-types = { version = "0.2.9", features = ["derive"] }
cornucopia_sync = "0.4.0"