name: Rust-CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/*"
      - "feature/*"
    paths:
      - "crates/*/src/**"
      - ".github/workflows/rust-ci.yml"
  pull_request:
    branches:
      - main
      - "release/*"
      - "feature/*"
    paths:
      - "crates/*/src/**"
      - ".github/workflows/rust-ci.yml"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        BUILD_TARGET: [ release ]
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Temporarily modify the rust toolchain version
        run: rustup override set stable
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Output rust version for educational purposes
        run: rustup --version
      - name: Cache
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/debug
            target/release
          key: ${{ runner.os }}-cargo
      - name: CheckOut
        uses: actions/checkout@v4
      - name: Run tests
        run: cargo test -p domain-manager
      - name: Build binaries
        run: cargo build -p domain-manager --release