name: Rust-CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "crates/*/src/**"
      - ".github/workflows/rust-ci.yml"
  pull_request:
    branches:
      - main
    paths:
      - "crates/*/src/**"
      - ".github/workflows/rust-ci.yml"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1

jobs:
  build-and-test:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        os: [ windows-latest ]
        BUILD_TARGET: [ release ]
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Temporarily modify the rust toolchain version
        run: rustup override set stable
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Output rust version for educational purposes
        run: rustup --version
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: CheckOut
        uses: actions/checkout@v6
      - name: Run Check
        run: cargo check -p domain-manager
      - name: Run Test
        run: cargo test -p domain-manager