name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build -p http_server --release --verbose
      - name: Build Domain Manager
        run: cargo build -p domain_manager --release --verbose
#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag learn-rust:$(date +%s)
